export const PLAYER_SCORE_WEIGHTS = {
  goalWeight: 6,
  assistWeight: 4,
  pointWeight: 1,
} as const;

export const PLAYER_NAME_MAPPING: Record<string, string> = {
  David: 'Frič David',
  Dvaid: 'Frič David',
  Milan: 'Hurtík Milan',
  Viktor: 'Jurdič Viktor',
  Zbyněk: 'Laisek Zbyněk',
  Jirka: 'Matějka Jiří',
  Jiří: 'Matějka Jiří',
  Richard: 'Mišaga Richard',
  'Honza O.': 'Osička Jan',
  'Honza O': 'Osička Jan',
  'Honza T.': 'Tuček Jan',
  'Honza T': 'Tuček Jan',
  Honza: 'Osička Jan',
  Jan: 'Osička Jan',
  'Ondra Vá.': 'Vácha Ondra',
  'Ondra Va': 'Vácha Ondra',
  Ondra: 'Vácha Ondra',
  Petr: 'Rajtšlégr Petr',
  'Tomáš M.': 'Máka Tomáš',
  'Tomáš M': 'Máka Tomáš',
  Tomáš: 'Máka Tomáš',
  Luboš: 'Burdík Luboš',
  Martin: 'Anděl Martin',
};
