import { calculatePlayerScore } from './teamSelection';
import { Player } from './xlsxParser';

export const getOnFirePlayer = (players: Player[]): Player | null => {
  if (players.length === 0) return null;

  return players.reduce((maxPlayer, currentPlayer) =>
    calculatePlayerScore(currentPlayer) > calculatePlayerScore(maxPlayer)
      ? currentPlayer
      : maxPlayer,
  );
};

export const onFireQuotes = [
  'is hotter than a jalapeño in a sauna!',
  'is scoring more than a calculator on steroids!',
  "is so on fire, they're melting the turf!",
  "is playing like they've got cheat codes enabled!",
  'is dominating the field like a boss in easy mode!',
  "is so good, they make the rest look like they're playing in slow motion!",
  "is on such a hot streak, they're setting off smoke alarms!",
  "is playing like they've got rocket boots and a magic ball!",
  'is so unstoppable, they might be part cyborg!',
  'is making the opposition look like training cones out there!',
  'is breaking records faster than a DJ scratches vinyl!',
  'is leaving defenders more confused than a chameleon in a bag of Skittles!',
  'is so precise, they could thread a needle with a football!',
  'is playing 4D chess while everyone else is playing checkers!',
  "is moving so fast, they're bending the space-time continuum!",
  'is scoring goals like it\'s a video game set to "Easy" mode!',
  "is so slick, they're making the pitch look like an ice rink!",
  'is defying gravity more than an astronaut in zero-G!',
  'is reading the game so well, they must have ESPN... I mean ESP!',
  'is leaving the defense more shook than a polaroid picture!',
  'is performing magic tricks with the ball that would make Houdini jealous!',
  'is so smooth on the field, they make butter look chunky!',
  "is scoring so much, they're single-handedly causing scoreboard malfunctions!",
  'is playing with such finesse, they could dribble through a china shop without breaking a thing!',
  'is so fast, they leave afterimages like a comic book speedster!',
  'is making passes so accurate, GPS systems are asking for tips!',
  'is juking defenders out of their shoes... and socks... and shin guards!',
  'is playing like they have eyes in the back of their head... and on their feet!',
  'is so dominant, the opposing team is considering calling in the National Guard!',
  'is weaving through defenses like a seamstress on a caffeine rush!',
  'is striking the ball with the precision of a surgeon and the power of a heavyweight champ!',
  'is pulling off moves that belong in a kung fu movie, not a soccer match!',
  'is so elusive, they could dodge raindrops in a thunderstorm!',
  'is making the ball obey commands like a well-trained puppy!',
  'is playing with such intensity, they might spontaneously combust at any moment!',
  'is leaving opponents so dizzy, they\'re considering installing "Do Not Enter" signs around them!',
  'is defying the laws of physics more often than a cartoon character!',
  'is orchestrating plays so beautiful, Mozart would be taking notes!',
  'is more unpredictable than a weather forecast in tornado alley!',
  'is rewriting the soccer rulebook with every touch of the ball!',
  "is making the ball defy gravity like it's in a sci-fi movie!",
  "is so hot right now, they're making the stadium sprinklers activate!",
  "is playing like they've got an invisible force field around them!",
  'is leaving defenders spinning like tops in a tornado!',
  'is so accurate, they could score from the parking lot!',
  'is making the opposition question their career choices!',
  "is playing like they've got a crystal ball predicting every move!",
  "is so fast, they're leaving scorch marks on the pitch!",
  'is pulling off moves that would make a contortionist jealous!',
  'is dominating so hard, the other team is considering early retirement!',
  "is playing like they've got magnets in their boots and the ball is made of metal!",
  'is so elusive, they could hide from a search party in an empty room!',
  "is making the game look easier than a toddler's puzzle!",
  "is breaking ankles like they're made of peanut brittle!",
  "is so dominant, they're making the scoreboard operator work overtime!",
  "is playing like they've got a personal gravity switch!",
  'is leaving defenders more twisted than a pretzel in a yoga class!',
  'is so precise, they could write calligraphy with a soccer ball!',
  'is making passes so smooth, they should come with a "slippery when wet" sign!',
  "is playing like they've got an extra pair of invisible legs!",
  "is so unstoppable, they're making brick walls look like tissue paper!",
  'is dribbling through defenses like a hot knife through butter... on a summer day... in Death Valley!',
  "is reading plays so well, they must have stolen the other team's playbook... and added some cheat codes!",
  "is moving so fast, they're creating their own wind tunnel effect!",
  "is juking with such finesse, they're making defenders question the laws of physics!",
  'is striking the ball with more precision than a Swiss watchmaker on espresso!',
  "is so dominant, they're making the rest of the league consider a career change to competitive knitting!",
  "is playing like they've got a personal highlight reel editor following them around!",
  "is leaving opponents so baffled, they're considering hiring a private detective to figure out their secrets!",
  'is defying expectations more than a cat learning to bark!',
  'is making such incredible plays, even the referees are asking for autographs!',
  'is so smooth on the field, they make silk look like sandpaper!',
  "is playing with more tricks up their sleeve than a magician's convention!",
  "is so fast, they're making light consider taking speed lessons!",
  'is dominating the game like a chess grandmaster playing against a bunch of pigeons!',
  'is pulling off moves that belong in a Matrix movie, not a soccer match!',
  'is so elusive, they could play hide-and-seek in a phone booth and win!',
  'is striking fear into defenders like a lion at a vegetarian convention!',
  'is orchestrating plays so intricate, they should come with an instruction manual!',
  'is rewriting soccer strategy faster than a supercomputer on overdrive!',
];

export const getRandomQuote = (): string => {
  return onFireQuotes[Math.floor(Math.random() * onFireQuotes.length)];
};
